### ISSUE TITLE
How do I use this with blade components?

### ISSUE THREAD

**Issue by seabasss** [danharrin/alpine-mousetrap#1]
Handy little thing, thanks!

I get this error in my blade file:
```
syntax error, unexpected token "endif", expecting end of file
```
Any way to get around that when working with blade components?
```
<x-button x-mousetrap.ctrl+n>Button</x-button>
```

Do I need to set an attribute that is `keycommand="x-mousetrap.ctrl+n"` and add the property inside the component if set?

Thanks!

**Comment by danharrin** [comment]
Ah interesting, maybe . or + are illegal characters in Blade component attributes.

Maybe you should pass through `:keybindings="['ctrl+n']"`, and then in the component view:

```blade
@if ($keybindings)
    x-mousetrap.{{ implode('.', $keybindings) }}
@endif
```

**Comment by seabasss** [comment]
Ok cool, that's kind of what I was thinking. Thanks!

How would you treat this? 
``
x-mousetrap.command+k.ctrl+k="console.log('command k or control k')"
```

Not sure what to do in the case I want a function along with it, but maybe that's another if statement inside the component.

**Comment by danharrin** [comment]
Hmm, maybe something like `:keybindings="['ctrl+n' => 'console.log(\'command k or control k\')']"`, whatever syntax you wish really!

**Comment by seabasss** [comment]
> Hmm, maybe something like `:keybindings="['ctrl+n' => 'console.log(\'command k or control k\')']"`, whatever syntax you wish really!

Sweet! Thanks!
